name: Automated Testing
on: 
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-unit-tests:
    name: Run All Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout under $GITHUB_WORKSPACE
        uses: actions/checkout@main

      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install all dependencies
        run: npm install

      - name: Run Unit Tests
        run: npm run test-unit

      - name: Run E2E Tests
        run: npm run cy:run
