name: Deploy static content to Pages

on:
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Static Content
        # Add your build steps here, if needed

      - name: Configure Pages
        uses: actions/configure-pages@v3
        with:
          target_branch: gh-pages
          folder: path/to/static-content # Replace with your content directory

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: path/to/static-content # Replace with your content directory

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
